<?php

namespace ContainerKER0GNq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSizeControllergetSizesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0OVTmbO.App\Controller\SizeController::getSizes()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0OVTmbO.App\\Controller\\SizeController::getSizes()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sizeRepository' => ['privates', 'App\\Repository\\SizeRepository', 'getSizeRepositoryService', true],
        ], [
            'sizeRepository' => 'App\\Repository\\SizeRepository',
        ]))->withContext('App\\Controller\\SizeController::getSizes()', $container);
    }
}
