<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVkrO5PP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVkrO5PP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVkrO5PP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVkrO5PP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVkrO5PP\App_KernelDevDebugContainer([
    'container.build_hash' => 'VkrO5PP',
    'container.build_id' => 'e9fce52d',
    'container.build_time' => 1740758669,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVkrO5PP');
