<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO77X6mH\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO77X6mH/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerO77X6mH.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerO77X6mH\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerO77X6mH\App_KernelDevContainer([
    'container.build_hash' => 'O77X6mH',
    'container.build_id' => 'a2376c17',
    'container.build_time' => 1740735143,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO77X6mH');
