<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY214Yxb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY214Yxb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY214Yxb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY214Yxb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY214Yxb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y214Yxb',
    'container.build_id' => '9443c016',
    'container.build_time' => 1741096652,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY214Yxb');
