<?php

namespace ContainerS63jtDZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LeMtnKvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.leMtnKv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.leMtnKv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.A84gqGd.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\TraderRegisterController::registerTrader' => ['privates', '.service_locator.eVyf.CT.App\\Controller\\TraderRegisterController::registerTrader()', 'getTraderRegisterControllerregisterTraderService', true],
            'App\\Controller\\UserRegisterController::register' => ['privates', '.service_locator.eVyf.CT.App\\Controller\\UserRegisterController::register()', 'getUserRegisterControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.A84gqGd.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\TraderRegisterController:registerTrader' => ['privates', '.service_locator.eVyf.CT.App\\Controller\\TraderRegisterController::registerTrader()', 'getTraderRegisterControllerregisterTraderService', true],
            'App\\Controller\\UserRegisterController:register' => ['privates', '.service_locator.eVyf.CT.App\\Controller\\UserRegisterController::register()', 'getUserRegisterControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\TraderRegisterController::registerTrader' => '?',
            'App\\Controller\\UserRegisterController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\TraderRegisterController:registerTrader' => '?',
            'App\\Controller\\UserRegisterController:register' => '?',
        ]);
    }
}
