<?php

namespace ContainerS63jtDZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTraderRegisterControllerregisterTraderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eVyf.CT.App\Controller\TraderRegisterController::registerTrader()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eVyf.CT.App\\Controller\\TraderRegisterController::registerTrader()'] = ($container->privates['.service_locator.eVyf.CT'] ?? $container->load('get_ServiceLocator_EVyf_CTService'))->withContext('App\\Controller\\TraderRegisterController::registerTrader()', $container);
    }
}
