<?php

namespace ContainerY214Yxb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountControllergetDiscountsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.miUSQzh.App\Controller\DiscountController::getDiscounts()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.miUSQzh.App\\Controller\\DiscountController::getDiscounts()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'discountRepository' => ['privates', 'App\\Repository\\DiscountRepository', 'getDiscountRepositoryService', true],
        ], [
            'discountRepository' => 'App\\Repository\\DiscountRepository',
        ]))->withContext('App\\Controller\\DiscountController::getDiscounts()', $container);
    }
}
