<?php

namespace ContainerY214Yxb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubCategoryControllergetSubCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..IVzQrD.App\Controller\SubCategoryController::getSubCategories()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..IVzQrD.App\\Controller\\SubCategoryController::getSubCategories()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'subCategoryRepository' => ['privates', 'App\\Repository\\SubCategoryRepository', 'getSubCategoryRepositoryService', true],
        ], [
            'subCategoryRepository' => 'App\\Repository\\SubCategoryRepository',
        ]))->withContext('App\\Controller\\SubCategoryController::getSubCategories()', $container);
    }
}
