<?php

namespace ContainerFSwLesx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I7qPdJrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i7qPdJr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i7qPdJr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\FavoriteController::addFavorite' => ['privates', '.service_locator.egipcEH.App\\Controller\\FavoriteController::addFavorite()', 'getFavoriteControlleraddFavoriteService', true],
            'App\\Controller\\FavoriteController::removeFavorite' => ['privates', '.service_locator.egipcEH.App\\Controller\\FavoriteController::removeFavorite()', 'getFavoriteControllerremoveFavoriteService', true],
            'App\\Controller\\FavoriteController::show' => ['privates', '.service_locator.KOxrz0D.App\\Controller\\FavoriteController::show()', 'getFavoriteControllershowService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.A84gqGd.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.Pvsz2ki.App\\Controller\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.Pvsz2ki.App\\Controller\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.MFPVaGP.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\TraderRegisterController::registerTrader' => ['privates', '.service_locator.eVyf.CT.App\\Controller\\TraderRegisterController::registerTrader()', 'getTraderRegisterControllerregisterTraderService', true],
            'App\\Controller\\UserRegisterController::register' => ['privates', '.service_locator.eVyf.CT.App\\Controller\\UserRegisterController::register()', 'getUserRegisterControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\FavoriteController:addFavorite' => ['privates', '.service_locator.egipcEH.App\\Controller\\FavoriteController::addFavorite()', 'getFavoriteControlleraddFavoriteService', true],
            'App\\Controller\\FavoriteController:removeFavorite' => ['privates', '.service_locator.egipcEH.App\\Controller\\FavoriteController::removeFavorite()', 'getFavoriteControllerremoveFavoriteService', true],
            'App\\Controller\\FavoriteController:show' => ['privates', '.service_locator.KOxrz0D.App\\Controller\\FavoriteController::show()', 'getFavoriteControllershowService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.A84gqGd.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.Pvsz2ki.App\\Controller\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.Pvsz2ki.App\\Controller\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.MFPVaGP.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\TraderRegisterController:registerTrader' => ['privates', '.service_locator.eVyf.CT.App\\Controller\\TraderRegisterController::registerTrader()', 'getTraderRegisterControllerregisterTraderService', true],
            'App\\Controller\\UserRegisterController:register' => ['privates', '.service_locator.eVyf.CT.App\\Controller\\UserRegisterController::register()', 'getUserRegisterControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\FavoriteController::addFavorite' => '?',
            'App\\Controller\\FavoriteController::removeFavorite' => '?',
            'App\\Controller\\FavoriteController::show' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\TraderRegisterController::registerTrader' => '?',
            'App\\Controller\\UserRegisterController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\FavoriteController:addFavorite' => '?',
            'App\\Controller\\FavoriteController:removeFavorite' => '?',
            'App\\Controller\\FavoriteController:show' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\TraderRegisterController:registerTrader' => '?',
            'App\\Controller\\UserRegisterController:register' => '?',
        ]);
    }
}
